# -*- coding: utf-8 -*-
"""model 3 resnet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-ezHqA9_Mw0gUC7d9K-cDjCkERkv1Ty
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

zip_path = "/content/drive/MyDrive/croppeddataset.zip"
extract_path = "/content/midas_images"

# extraction folder
os.makedirs(extract_path, exist_ok=True)

# Extract
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipped successfully!")

print(os.listdir("/content/midas_images"))

import glob

image_folder = "/content/midas_images/cropped dataset"

all_images = glob.glob(image_folder + "/*.jpg")

print("Total images found:", len(all_images))

import pandas as pd

excel_path = "/content/drive/MyDrive/release_midas.xlsx"
df_original = pd.read_excel(excel_path)

df_original.columns = df_original.columns.str.strip()

print("Total rows:", len(df_original))
print(df_original.head())

image_folder = "/content/midas_images/cropped dataset"

import os

actual_images = set(os.listdir(image_folder))

image_dict = {img: os.path.join(image_folder, img) for img in actual_images}

df = df_original.copy()
df['image_path'] = df['midas_file_name'].apply(lambda x: os.path.join(image_folder, x))

# cleaning data
df = df[df['image_path'].notna()]
df = df[df['image_path'].apply(os.path.exists)]

print("Final usable dataset:", len(df))

print(df['midas_melanoma'].unique())

print(df['midas_melanoma'].value_counts(dropna=False))

df = df[df['midas_melanoma'].notna()]
print(df['midas_melanoma'].isna().sum())

df['label'] = df['midas_melanoma'].str.lower().map({'yes': 1, 'no': 0})
print(df['label'].value_counts())

print("Melanoma cases:", sum(df['label'] == 1))
print("Benign cases:", sum(df['label'] == 0))

from sklearn.model_selection import StratifiedGroupKFold
import numpy as np

sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

X = df['image_path']
y = df['label'].astype(int)
groups = df['midas_record_id']

train_idx, val_idx = next(sgkf.split(X, y, groups))

train_df = df.iloc[train_idx].copy()
val_df = df.iloc[val_idx].copy()

print("Train size:",len(train_df))
print("Val size:",len(val_df))

train_df['label'] = train_df['label'].astype(str)
val_df['label']= val_df['label'].astype(str)

from sklearn.utils import class_weight
import numpy as np

class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_df['label']),
    y=train_df['label']
)

class_weight_dict = dict(enumerate(class_weights))

print("Class Weights:", class_weight_dict)

#image preprocessing

from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = 224

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    zoom_range=0.25,
    width_shift_range=0.15,
    height_shift_range=0.15,
    shear_range=0.15,
    horizontal_flip=True,
    brightness_range=[0.7,1.3]
    )

val_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

train_generator = train_datagen.flow_from_dataframe(
    train_df,
    x_col="image_path",
    y_col="label",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=32,
    class_mode="binary"
)

val_generator = val_datagen.flow_from_dataframe(
    val_df,
    x_col="image_path",
    y_col="label",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=32,
    class_mode="binary",
    shuffle=False
)

from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, Model, models

base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze initially
for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)

x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.5)(x)


output = layers.Dense(1, activation='sigmoid')(x)
model_resnet = Model(inputs=base_model.input, outputs=output)

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC

model_resnet.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy', AUC(name='auc')]
)

#earlystopping for model improvement

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stop = EarlyStopping(
    monitor='val_auc',
    mode='max',
    patience=5,
    restore_best_weights=True
)

lr_reduce = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=2,
    min_lr=1e-6
)

history_resnet = model_resnet.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20,
    callbacks=[early_stop, lr_reduce]
)

val_generator.reset()

y_pred_prob = model_resnet.predict(val_generator)
y_pred = (y_pred_prob > 0.5).astype(int)

y_true = val_generator.classes

# fine tuning

base_model.trainable = True

for layer in base_model.layers:
    if isinstance(layer, layers.BatchNormalization):
        layer.trainable = False

model_resnet.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy', AUC(name='auc')]
)

fine_history = model_resnet.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,
    callbacks=[early_stop, lr_reduce]
)

from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

# AUC
auc = roc_auc_score(y_true, y_pred_prob)
print("AUC:", auc)

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
tn, fp, fn, tp = cm.ravel()

sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

print("Sensitivity (Recall for Melanoma):", sensitivity)
print("Specificity (Benign detection rate):", specificity)

# report
print(classification_report(y_true, y_pred))

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_true, y_pred_prob)

plt.plot(fpr, tpr)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()